trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'artifact1/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'artifact1/target'
        ArtifactName: 'drop'
        publishLocation: 'Container'